# https://golangci-lint.run/docs/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - revive
    - errcheck
    - staticcheck
    - bodyclose
  settings:
    revive:
      rules:
        - name: package-comments
        - name: exported
        - name: var-naming
    errcheck:
      check-blank: false

issues:
  exclude-rules:
    - path: '_test\.go'
      linters:
        - revive
