package enums

var AllowedBPMNElements = []string{
	"definitions",
	"collaboration",
	"participant",
	"process",
	"laneSet",
	"lane",
	"flowNodeRef",
	"error",
	"message",
	"dataStoreReference",

	"task",
	"startEvent",
	"endEvent",
	"userTask",
	"sendTask",
	"receiveTask",
	"serviceTask",
	"parallelGateway",
	"exclusiveGateway",
	"inclusiveGateway",
	"eventBasedGateway",
	"subProcess",
	"callActivity",

	"boundaryEvent",
	"intermediateCatchEvent",
	"timerEventDefinition",
	"errorEventDefinition",
	"messageEventDefinition",
	"timeDuration",

	"sequenceFlow",
	"messageFlow",
	"extensionElements",
	"conditionExpression",
	"incoming",
	"outgoing",
}
